# HTTP Server
server:  
  port: ${PORT:8080}   # HTTP port

# Spring properties
spring:  
  application:
    name: RestService
eureka:  
  client:
    serviceUrl:
      defaultZone: http://springcloudnetflix-eurek-fusetest.apps.na311.openshift.opentlc.com/eureka/         
  instance:
      preferIpAddress: true          
          
