server:  
  address: x.x.x.x
  port: ${PORT:8080}   # HTTP port

# Spring properties
spring:  
  application:
    name: RestService
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
eureka:  
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://springcloudnetflix-eurek-fusetest.apps.na311.openshift.opentlc.com/eureka/         
          
          
